# -*- coding: utf-8 -*-
{
    'name': 'HR Attendance Shift Groups',
    'version': '18.0.1.41.0',
    'category': 'Human Resources/Attendances',
    'summary': 'Clasificacion automatica de horas, tablero diario por grupo, '
               'correccion de marcaciones, exportacion Excel/PDF, deteccion '
               'de FALTAS / vacaciones / fines de semana / feriados PY, '
               'workflow aprobacion de FALTAS.',
    'author': 'Crossnexion',
    'website': 'https://www.crossnexion.com',
    'license': 'LGPL-3',
    'depends': ['base', 'hr', 'hr_attendance', 'hr_contract', 'hr_holidays',
                'resource', 'mail'],
    'external_dependencies': {'python': ['xlsxwriter']},
    'data': [
        'security/hr_attendance_shift_security.xml',
        'security/ir.model.access.csv',
        'data/hr_shift_group_data.xml',
        'wizards/hr_attendance_shift_recompute_views.xml',
        'wizards/hr_attendance_shift_export_views.xml',
        'wizards/hr_attendance_fix_views.xml',
        'wizards/hr_falta_request_wizard_views.xml',
        'views/hr_shift_group_views.xml',
        'views/hr_employee_views.xml',
        'views/hr_attendance_views.xml',
        'views/hr_attendance_dashboard_views.xml',
        'views/hr_attendance_correction_views.xml',
        'views/hr_attendance_daily_report_views.xml',
        'views/hr_falta_justification_views.xml',
        'views/resource_calendar_views.xml',
        'report/hr_attendance_shift_pdf_report.xml',
        'report/hr_attendance_shift_pdf_template.xml',
        'report/hr_attendance_monthly_summary_report.xml',
        'report/hr_attendance_detail_es_report.xml',
        'report/hr_attendance_daily_report_pdf.xml',
        'views/menus.xml',
        'wizards/hr_attendance_detail_export_views.xml',
    ],
    'post_init_hook': 'post_init_load_py_holidays',
    'installable': True, 'application': False, 'auto_install': False,
}
