from . import sale_order
from . import sale_order_line
from . import order_detail_lines
from . import order_detail_model_lines
from . import model_type
from . import sale_stage
from . import technical_info
from . import model_design_history
from . import product_template
from . import product_category
from . import sale_order_template
from . import sale_detalles_config 