from . import hr_shift_group
from . import hr_shift_slot
from . import hr_employee
from . import hr_contract
from . import hr_attendance
from . import hr_attendance_shift_line
from . import hr_attendance_daily_report
from . import resource_calendar
from . import hr_falta_justification
from . import hr_leave
