# -*- coding: utf-8 -*-
{
    'name': 'Crossnexion - Inventario',
    'summary': 'Modulo que hereda del principal y ajusta al requerimiento del cliente',
    'author': 'Crossnexion EAS',
    'website': 'www.crossnexion.com',
    'license': 'OPL-1',
    'category': 'Uncategorized',
    'version': '26.4.20',
    'depends': [
        'base',
        'product',
        'sale_management',
        'utex_stock_landed_costs_cross',
        'sale_detalles',
        'electronic_invoice_cross',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'data/ir_sequence.xml',
        'data/paperformatticket.xml',
        'data/ir_actions_server.xml',
        'reports/report_delivery_ticket.xml',
        'views/product_template.xml',
        'views/product_product.xml',
        'views/product_brand.xml',
        'views/product_collection.xml',
        'views/product_initial.xml',
        'views/product_model.xml',
        'views/product_combination_fabrics.xml',
        'views/product_molding_size.xml',
        'views/product_molding_software.xml',
        'views/product_molding_parts.xml',
        'views/product_type_fabric.xml',
        'views/product_type_thread.xml',
        'views/product_molding_label.xml',
        'views/product_molding.xml',
        'views/product_gender.xml',
        'views/product_type_use.xml',
        'views/product_attribute_attribute.xml',
        'views/product_online_technology.xml',
        'views/product_name_sequence.xml',
        'views/res_config_settings.xml',
        'views/mrp_bom.xml',
        'views/product_design.xml',
        'views/stock_picking.xml',
        'views/product_attribute.xml',
        'views/sale_order_template.xml',
        'views/product_packaging.xml',
    ],
}
